// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import AiEnergyAnalystController from "./ai_energy_analyst_controller"
application.register("ai-energy-analyst", AiEnergyAnalystController)

import MobileAccountSheetController from "./mobile_account_sheet_controller"
application.register("mobile-account-sheet", MobileAccountSheetController)

import AlarmsSearchController from "./alarms_search_controller"
application.register("alarms-search", AlarmsSearchController)

import ReportDraftFromPromptController from "./report_draft_from_prompt_controller"
application.register("report-draft-from-prompt", ReportDraftFromPromptController)
