# frozen_string_literal: true

module EnergyAnalyst
  # Loads the static demo telemetry JSON exactly once per process and hands
  # back a deeply-frozen Hash. The JSON itself is generated by
  # `script/generate_company_a_telemetry.rb` (see that file for the dataset
  # contract, anomaly plan, and reference date).
  #
  # Production swap path: replace `load!` with a tenant-scoped query path
  # (RLS-aware ActiveRecord under `with_rls_context`) that returns the same
  # shape `TelemetryInsights` consumes. Everything downstream is shape-only.
  class TelemetryRepository
    DATA_PATH = Rails.root.join("config", "data", "company_a_telemetry.json")

    class << self
      def data
        @data ||= load!
      end

      # Test-only: drop the memoized payload so a fixture can be installed.
      def reset!
        @data = nil
      end

      # Test-only: install an in-memory payload (e.g. a small fixture).
      def install(payload)
        @data = deep_freeze(payload.deep_dup)
      end

      private

      def load!
        raw = File.read(DATA_PATH)
        deep_freeze(JSON.parse(raw, symbolize_names: true))
      rescue Errno::ENOENT, JSON::ParserError => e
        Rails.logger.error("[EnergyAnalyst] failed to load demo telemetry: #{e.class}: #{e.message}")
        raise
      end

      def deep_freeze(obj)
        case obj
        when Hash
          obj.each_value { |v| deep_freeze(v) }
          obj.freeze
        when Array
          obj.each { |v| deep_freeze(v) }
          obj.freeze
        else
          obj.freeze
        end
      end
    end
  end
end
